import dotenv from "dotenv";

dotenv.config();

/**
 * Executes a prompt using Gemini and returns structured data (JSON if possible).
 */
export async function runPrompt(prompt) {
  try {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error("GEMINI_API_KEY is missing from environment variables.");
    }

    const response = await fetch(
      "https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=" +
        process.env.GEMINI_API_KEY,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [{ text: prompt }]
            }
          ],
          generationConfig: {
            temperature: 0.1, // Keep it deterministic for logistics
            topP: 0.95,
            maxOutputTokens: 1024,
          }
        })
      }
    );

    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`Gemini API Error: ${response.status} - ${errorBody}`);
    }

    const data = await response.json();

    if (!data.candidates || data.candidates.length === 0) {
      throw new Error("No response generated by Gemini.");
    }

    const rawText = data.candidates[0].content.parts[0].text;

    // Clean markdown formatting if present
    const cleaned = rawText
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();

    // Try to parse as JSON, otherwise return as text
    try {
      return JSON.parse(cleaned);
    } catch (e) {
      return cleaned;
    }
  } catch (error) {
    console.error("❌ AI Module Error:", error.message);
    throw error;
  }
}

